# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2024 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Myra <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2025 ReserveBot <211949879+ReserveBot@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Svarshik <96281939+lexaSvarshik@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 nazrin <tikufaev@outlook.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Close PRs on master

on:
  pull_request_target:
    types: [ opened, ready_for_review ]

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{github.head_ref == 'master' || github.head_ref == 'main' || github.head_ref == 'develop'}}

    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Благодарим вас за вклад в репозиторий Reserve Station. К сожалению, похоже, что вы отправили свой запрос на исправление из мастер-ветки, это [что-то, чего вам не стоит делать](https://jmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/), и таким образом PR был автоматически закрыт. Мы предлагаем вам следовать [нашей документации по использованию git](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html) \n\n Вы можете перенести текущую работу из мастер-ветки в другую ветку, выполнив [эти команды] (https://ohshitgit.com/#accidental-commit-master). Затем вы можете воссоздать свой PR с помощью новой ветки." #Reserve edit

    # If you prefer to just comment on the pr and not close it, uncomment the bellow and comment the above

    # - uses: actions/github-script@v7
    #   with:
    #     script: |
    #       github.rest.issues.createComment({
    #         issue_number: ${{ github.event.number }},
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: "Thank you for contributing to the Goob Station repository. Unfortunately, it looks like you submitted your pull request from the master branch. We suggest you follow [our git usage documentation](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html) \n\n You can move your current work from the master branch to another branch by doing `git branch <branch_name` and resetting the master branch. \n\n This pr won't be automatically closed. However, a maintainer may close it for this reason."
    #       })
